2022-02-08 16:13:29,056 INFO    MainThread:832 [wandb_setup.py:_flush():75] Loading settings from C:\Users\kausach\.config\wandb\settings
2022-02-08 16:13:29,056 INFO    MainThread:832 [wandb_setup.py:_flush():75] Loading settings from C:\Users\kausach\PycharmProjects\NerBERT_HuggingFace\wandb\settings
2022-02-08 16:13:29,056 INFO    MainThread:832 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-02-08 16:13:29,057 INFO    MainThread:832 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-02-08 16:13:29,057 INFO    MainThread:832 [wandb_init.py:_log_setup():386] Logging user logs to C:\Users\kausach\PycharmProjects\NerBERT_HuggingFace\wandb\run-20220208_161329-wedzhvge\logs\debug.log
2022-02-08 16:13:29,058 INFO    MainThread:832 [wandb_init.py:_log_setup():387] Logging internal logs to C:\Users\kausach\PycharmProjects\NerBERT_HuggingFace\wandb\run-20220208_161329-wedzhvge\logs\debug-internal.log
2022-02-08 16:13:29,059 INFO    MainThread:832 [wandb_init.py:init():420] calling init triggers
2022-02-08 16:13:29,059 INFO    MainThread:832 [wandb_init.py:init():425] wandb.init called with sweep_config: {}
config: {}
2022-02-08 16:13:29,060 INFO    MainThread:832 [wandb_init.py:init():471] starting backend
2022-02-08 16:13:29,060 INFO    MainThread:832 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2022-02-08 16:13:29,065 INFO    MainThread:832 [backend.py:ensure_launched():219] starting backend process...
2022-02-08 16:13:29,089 ERROR   MainThread:832 [wandb_init.py:init():978] error
Traceback (most recent call last):
  File "C:\Users\kausach\PycharmProjects\NerBERT_HuggingFace\venv\lib\site-packages\wandb\sdk\wandb_init.py", line 951, in init
    run = wi.init()
  File "C:\Users\kausach\PycharmProjects\NerBERT_HuggingFace\venv\lib\site-packages\wandb\sdk\wandb_init.py", line 478, in init
    backend.ensure_launched()
  File "C:\Users\kausach\PycharmProjects\NerBERT_HuggingFace\venv\lib\site-packages\wandb\sdk\backend\backend.py", line 222, in ensure_launched
    self.wandb_process.start()
  File "C:\Users\kausach\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\kausach\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\kausach\AppData\Local\Programs\Python\Python39\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\kausach\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\kausach\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
